
import { get, post, put, del } from './apiClient';
import { College } from '@/types/college';

// Get all colleges
export const fetchColleges = () => 
  get<College[]>('/api/colleges');

// Get a single college by ID
export const fetchCollegeById = (id: number) => 
  get<College>(`/api/colleges/${id}`);

// Get colleges that offer a specific degree
export const fetchCollegesByDegree = (degreeId: number) => 
  get<College[]>(`/api/colleges/degree/${degreeId}`);

// Get featured colleges
export const fetchFeaturedColleges = () =>
  get<College[]>('/api/colleges/featured');

// Get Bangalore colleges
export const fetchBangaloreColleges = () =>
  get<College[]>('/api/colleges/bangalore');

// Get Karnataka colleges (full list)
export const fetchKarnatakaColleges = () =>
  get<College[]>('/api/colleges/karnataka');

// Admin functions (require authentication)

// Create a new college
export const createCollege = (collegeData: Omit<College, 'id'>) => 
  post<College>('/api/colleges', collegeData, true);

// Update an existing college
export const updateCollege = (id: number, collegeData: Partial<College>) => 
  put<College>(`/api/colleges/${id}`, collegeData, true);

// Delete a college
export const deleteCollege = (id: number) => 
  del<null>(`/api/colleges/${id}`, true);

// Get colleges in Karnataka from the list (for fallback)
export const getKarnatakaCollegesList = (): College[] => {
  // This provides a fallback list of colleges when the API is unavailable
  const colleges: College[] = [
    // First 10 colleges (original)
    { id: 1001, collegeCode: "E001", name: "Acharya Institute of Technology", location: "Soladevanahalli, Bengaluru, KARNATAKA", description: "Acharya Institute of Technology is an engineering college in Bengaluru offering various undergraduate and postgraduate programs.", rating: 4.2, fees: "₹85,000 - ₹1,50,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 4] },
    { id: 1002, collegeCode: "E003", name: "A.C.S. College of Engineering", location: "Kambipura (Mysore Road), Bengaluru, KARNATAKA", description: "A.C.S. College of Engineering provides quality education in engineering and technology fields.", rating: 4.0, fees: "₹75,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1003, collegeCode: "E004", name: "Adichunchanagiri Institute Of Technology", location: "Jyothi Nagara, Chikkamagaluru, KARNATAKA", description: "Adichunchanagiri Institute Of Technology offers various engineering courses with modern infrastructure.", rating: 4.1, fees: "₹70,000 - ₹1,10,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 6] },
    { id: 1004, collegeCode: "E005", name: "Akash Institute of Engineering and Technology", location: "Devanahalli, Bengaluru Rural, KARNATAKA", description: "Akash Institute focuses on providing technical education with industry exposure.", rating: 3.9, fees: "₹65,000 - ₹1,00,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 4] },
    { id: 1005, collegeCode: "E006", name: "Alva's Institute of Engineering & Technology", location: "Moodbidri, Mangaluru, KARNATAKA", description: "Alva's Institute is known for its excellence in engineering education and research.", rating: 4.3, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 7] },
    { id: 1006, collegeCode: "E007", name: "AMC Engineering College", location: "Bannerghatta Road, Bengaluru, KARNATAKA", description: "AMC Engineering College offers various engineering programs with state-of-the-art facilities.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1007, collegeCode: "E009", name: "Angadi Institute of Technology and Management", location: "Savagaon Road, Belagavi, KARNATAKA", description: "Angadi Institute provides quality technical education with modern infrastructure.", rating: 3.8, fees: "₹60,000 - ₹1,00,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 4] },
    { id: 1008, collegeCode: "E011", name: "APS College of Engineering", location: "Kanakapura Road, Bengaluru, KARNATAKA", description: "APS College of Engineering is committed to providing quality engineering education.", rating: 3.9, fees: "₹70,000 - ₹1,10,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 6] },
    { id: 1009, collegeCode: "E012", name: "Atria Institute of Technology", location: "Hebbal, Bengaluru, KARNATAKA", description: "Atria Institute of Technology offers various engineering and management programs.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 5] },
    { id: 1010, collegeCode: "E013", name: "Akshaya Institute of Technology", location: "Koratagere Road, Tumakuru, KARNATAKA", description: "Akshaya Institute focuses on holistic development of students through quality education.", rating: 3.7, fees: "₹60,000 - ₹1,00,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 4, 7] },
    
    // Adding 100 more colleges from the list
    { id: 1011, collegeCode: "E014", name: "Bharatesh Institute of Technology", location: "Shindholli Cross, Belagavi, KARNATAKA", description: "Bharatesh Institute of Technology offers quality engineering education with modern facilities.", rating: 3.9, fees: "₹65,000 - ₹1,10,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1012, collegeCode: "E015", name: "B.N.M. Institute of Technology", location: "Banashankari, Bengaluru, KARNATAKA", description: "B.N.M. Institute of Technology is known for its quality education and placement opportunities.", rating: 4.3, fees: "₹90,000 - ₹1,50,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 7] },
    { id: 1013, collegeCode: "E016", name: "KLE Technological University", location: "Vidyanagar, Hubbali, KARNATAKA", description: "Formerly known as BVBCET, KLE Technological University is a renowned institution for engineering education.", rating: 4.4, fees: "₹85,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 7] },
    { id: 1014, collegeCode: "E017", name: "Ballari Institute of Technology & Management", location: "Near Allipura, Ballari, KARNATAKA", description: "BITM offers quality technical education with a focus on industry-ready skills.", rating: 4.0, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 5] },
    { id: 1015, collegeCode: "E018", name: "Bangalore College of Engineering & Technology", location: "Chandapura, Bengaluru, KARNATAKA", description: "BCET provides engineering education with modern infrastructure and experienced faculty.", rating: 3.8, fees: "₹65,000 - ₹1,10,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 4] },
    { id: 1016, collegeCode: "E019", name: "Bangalore Institute of Technology", location: "V V Puram, Bengaluru, KARNATAKA", description: "BIT is one of the oldest engineering colleges in Bangalore with strong industry connections.", rating: 4.5, fees: "₹90,000 - ₹1,60,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 7] },
    { id: 1017, collegeCode: "E020", name: "Bangalore Technological Institute", location: "Chikkanayakanahalli Dinne, Bengaluru, KARNATAKA", description: "BTI focuses on providing quality technical education with practical exposure.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 5, 7] },
    { id: 1018, collegeCode: "E021", name: "Bapuji Institute of Engineering & Technology", location: "Shamanur Road, Davangere, KARNATAKA", description: "BIET offers various engineering programs with a focus on holistic development.", rating: 4.1, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 6] },
    { id: 1019, collegeCode: "E023", name: "Basavakalyan Engineering College", location: "NH9 Basavakalyan, Bidar, KARNATAKA", description: "BEC provides quality education in various engineering disciplines.", rating: 3.7, fees: "₹60,000 - ₹1,00,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 4, 5] },
    { id: 1020, collegeCode: "E024", name: "Basaveshwar Engineering College", location: "Vidyanagar, Bagalkot, KARNATAKA", description: "BEC is known for its academic excellence and research facilities.", rating: 4.2, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3] },
    { id: 1021, collegeCode: "E026", name: "BLDEA's V.P. Dr. P.G. Halakatti College of Engineering & Technology", location: "Ashram Road, Vijayapura, KARNATAKA", description: "BLDEA's college offers quality engineering education with state-of-the-art infrastructure.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 7] },
    { id: 1022, collegeCode: "E027", name: "BMS College of Engineering", location: "Basavanagudi, Bengaluru, KARNATAKA", description: "BMSCE is one of the oldest and most prestigious engineering colleges in Karnataka.", rating: 4.7, fees: "₹1,00,000 - ₹1,80,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 7] },
    { id: 1023, collegeCode: "E028", name: "BMS Institute of Technology & Management", location: "Yelahanka, Bengaluru, KARNATAKA", description: "BMSIT&M offers various engineering and management programs with excellent placement opportunities.", rating: 4.4, fees: "₹90,000 - ₹1,60,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 5, 7] },
    { id: 1024, collegeCode: "E030", name: "Brindavan College of Engineering", location: "Yelahanka, Bengaluru, KARNATAKA", description: "Brindavan College focuses on providing quality technical education with industry exposure.", rating: 3.8, fees: "₹65,000 - ₹1,10,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 4] },
    { id: 1025, collegeCode: "E032", name: "C.M.R. Institute of Technology", location: "Brookefield, Bengaluru, KARNATAKA", description: "CMRIT is known for its excellent infrastructure and quality education.", rating: 4.3, fees: "₹85,000 - ₹1,50,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 5] },
    { id: 1026, collegeCode: "E033", name: "Cambridge Institute of Technology", location: "K R Puram, Bengaluru, KARNATAKA", description: "CIT offers various engineering and management programs with modern facilities.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 7] },
    { id: 1027, collegeCode: "E035", name: "Channabasaveshwara Institute of Technology", location: "Gubbi, Tumakuru, KARNATAKA", description: "CIT provides quality education in various engineering disciplines.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1028, collegeCode: "E036", name: "Chanakya University", location: "Devanahalli, Bengaluru Rural, KARNATAKA", description: "Chanakya University offers multidisciplinary programs with a focus on innovation and research.", rating: 4.2, fees: "₹85,000 - ₹1,50,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 4, 8] },
    { id: 1029, collegeCode: "E037", name: "City Engineering College", location: "Doddakalasandra, Bengaluru, KARNATAKA", description: "City Engineering College focuses on providing quality technical education.", rating: 3.8, fees: "₹65,000 - ₹1,10,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 5, 7] },
    { id: 1030, collegeCode: "E038", name: "Coorg Institute of Technology", location: "Ponnampet, South Kodagu, KARNATAKA", description: "CIT offers various engineering programs in a serene environment.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 6] },
    { id: 1031, collegeCode: "E039", name: "Dayananda Sagar Academy of Technology & Management", location: "Kanakapura Road, Bengaluru, KARNATAKA", description: "DSATM offers quality education in engineering and management with excellent infrastructure.", rating: 4.2, fees: "₹85,000 - ₹1,50,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 5] },
    { id: 1032, collegeCode: "E040", name: "Dayananda Sagar College of Engineering", location: "Kumaraswamy Layout, Bengaluru, KARNATAKA", description: "DSCE is known for its academic excellence and placement opportunities.", rating: 4.5, fees: "₹95,000 - ₹1,70,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 7] },
    { id: 1033, collegeCode: "E041", name: "DON BOSCO Institute of Technology", location: "Kumbalgodu, Bengaluru, KARNATAKA", description: "DBIT provides quality technical education with a focus on practical skills.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1034, collegeCode: "E042", name: "Dr. Ambedkar Institute of Technology", location: "Malathahalli, Bengaluru, KARNATAKA", description: "Dr. AIT offers various engineering programs with modern infrastructure.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 7] },
    { id: 1035, collegeCode: "E043", name: "Yenepoya Institute of Technology", location: "Moodbidri, Mangaluru, KARNATAKA", description: "Formerly known as Dr. M V Shetty Institute of Technology, YIT offers quality technical education.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 6] },
    { id: 1036, collegeCode: "E044", name: "Dr.Shri Shri Shivakumara Mahaswamy College of Engineering", location: "Nelamangala, Bengaluru Rural, KARNATAKA", description: "DSSM offers various engineering programs with experienced faculty.", rating: 3.8, fees: "₹65,000 - ₹1,10,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 5, 7] },
    { id: 1037, collegeCode: "E045", name: "Dr H N National College Of Engineering", location: "Jayanagar Bengaluru, KARNATAKA", description: "HNNCE provides quality education in various engineering disciplines.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3] },
    { id: 1038, collegeCode: "E046", name: "East Point College of Engineering and Technology", location: "Avalahalli, Bengaluru, KARNATAKA", description: "EPCET offers quality technical education with modern infrastructure.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1039, collegeCode: "E048", name: "East West Institute of Technology", location: "BEL Layout, Bengaluru, KARNATAKA", description: "EWIT provides quality engineering education with a focus on practical skills.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 7] },
    { id: 1040, collegeCode: "E049", name: "Garden City University", location: "Old Madras Road, Bengaluru, KARNATAKA", description: "GCU offers various programs in engineering, management, and other disciplines.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 4, 8] },
    { id: 1041, collegeCode: "E050", name: "Global Academy of Technology", location: "Rajarajeshwari Nagar, Bengaluru, KARNATAKA", description: "GAT provides quality technical education with excellent infrastructure.", rating: 4.2, fees: "₹85,000 - ₹1,50,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5, 7] },
    { id: 1042, collegeCode: "E051", name: "GM Institute of Technology", location: "P B Road, Davangere, KARNATAKA", description: "GMIT offers various engineering programs with experienced faculty.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 6] },
    { id: 1043, collegeCode: "E053", name: "Gopalan College of Engineering And Management", location: "Whitefield, Bengaluru, KARNATAKA", description: "GCEM provides quality education in engineering and management fields.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 5] },
    { id: 1044, collegeCode: "E055", name: "GSSS Institute of Engineering and Technology for Women", location: "Metagalli, Mysuru, KARNATAKA", description: "GSSSIETW is a premier women's engineering college offering various technical programs.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 7] },
    { id: 1045, collegeCode: "E056", name: "H.K.E.Society's P.D.A. College of Engineering", location: "Aiwan E Shahi area, Kalaburgi, KARNATAKA", description: "PDA College offers quality technical education with modern facilities.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 5, 7] },
    { id: 1046, collegeCode: "E058", name: "Sri Jayachamarajendra College of Engineering", location: "Manasagangothri, Mysuru, KARNATAKA", description: "A constituent college of JSS Science and Technology University, SJCE is known for its academic excellence.", rating: 4.6, fees: "₹1,00,000 - ₹1,80,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 7] },
    { id: 1047, collegeCode: "E059", name: "Jawaharlal Nehru New College of Engineering", location: "Swalanga Road, Shivamogga, KARNATAKA", description: "JNNCE offers various engineering programs with excellent infrastructure.", rating: 4.2, fees: "₹85,000 - ₹1,50,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1048, collegeCode: "E060", name: "JSS Academy of Technical Education", location: "Kengeri Main Road, Bengaluru, KARNATAKA", description: "JSSATE provides quality technical education with a focus on practical skills.", rating: 4.3, fees: "₹90,000 - ₹1,60,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 7] },
    { id: 1049, collegeCode: "E061", name: "JSS Science & Technology University", location: "Mysuru, KARNATAKA", description: "JSS S&TU offers various programs in science, engineering, and technology fields.", rating: 4.5, fees: "₹95,000 - ₹1,70,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 5] },
    { id: 1050, collegeCode: "E062", name: "Jain College of Engineering", location: "T.S Nagar, Belagavi, KARNATAKA", description: "JCE offers quality technical education with modern infrastructure.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 7] },
    { id: 1051, collegeCode: "E063", name: "Jnana Vikas Institute of Technology", location: "Bidadi, Ramnagar Taluk, Bengaluru Rural, KARNATAKA", description: "JVIT provides quality engineering education with experienced faculty.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 5, 6] },
    { id: 1052, collegeCode: "E064", name: "Jain College Of Engineering & Research", location: "Udyambag, Belagavi, KARNATAKA", description: "JCER offers various engineering programs with a focus on research and innovation.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 7] },
    { id: 1053, collegeCode: "E065", name: "KLE Technological University", location: "Udyambag, Belagavi, KARNATAKA", description: "Formerly called as KLE Dr. M.S. sheshgiri college of Engineering and Technology, KLETU offers quality education.", rating: 4.4, fees: "₹90,000 - ₹1,60,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 7] },
    { id: 1054, collegeCode: "E066", name: "KLE College of Engineering and Technology", location: "Chikodi Dist., Belagavi, KARNATAKA", description: "KLECET provides quality technical education with modern facilities.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1055, collegeCode: "E067", name: "K.S School of Engineering And Management", location: "Off Kanakapura Road, Bengaluru, KARNATAKA", description: "KSSEM offers various engineering and management programs with experienced faculty.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 7] },
    { id: 1056, collegeCode: "E068", name: "K.S. Institute of Technology", location: "Kanakapura Main Road, Bengaluru, KARNATAKA", description: "KSIT provides quality engineering education with a focus on practical skills.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1057, collegeCode: "E069", name: "KVG College Of Engineering", location: "Sullia, Dakshina Kannada, KARNATAKA", description: "KVGCE offers quality technical education with excellent infrastructure.", rating: 4.2, fees: "₹85,000 - ₹1,50,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 7] },
    { id: 1058, collegeCode: "E070", name: "Kalpataru Institute of Technology", location: "B H Road, Tiptur, KARNATAKA", description: "KIT provides quality engineering education with experienced faculty.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 5, 6] },
    { id: 1059, collegeCode: "E071", name: "Karavali Institute of Technology", location: "Kottara, Mangaluru, KARNATAKA", description: "KIT offers various engineering programs with modern facilities.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 7] },
    { id: 1060, collegeCode: "E072", name: "KLE Society's K.L.E. Institute of Technology", location: "Gokul, Hubbali, KARNATAKA", description: "KLEIT provides quality technical education with a focus on innovation.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 5] },
    { id: 1061, collegeCode: "E073", name: "KLS Gogte Institute of Technology", location: "Udyambag, Belagavi, KARNATAKA", description: "GIT is known for its academic excellence and research facilities.", rating: 4.3, fees: "₹90,000 - ₹1,60,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 7] },
    { id: 1062, collegeCode: "E074", name: "KLS's. Vishwanathrao Deshpande Institute of Technology", location: "Dandeli Road, Haliyal, KARNATAKA", description: "VDIT offers quality engineering education with modern infrastructure.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 5, 7] },
    { id: 1063, collegeCode: "E075", name: "K. N. S. INSTITUTE OF TECHNOLOGY", location: "Yelahanka, Bengaluru, KARNATAKA", description: "KNSIT provides quality technical education with experienced faculty.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 5] },
    { id: 1064, collegeCode: "E076", name: "M.S. Engineering College", location: "Sadahalli, Bengaluru, KARNATAKA", description: "MSEC offers various engineering programs with a focus on practical skills.", rating: 3.8, fees: "₹65,000 - ₹1,10,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 6] },
    { id: 1065, collegeCode: "E077", name: "M.S. Ramaiah Institute of Technology", location: "MSR Nagar, Bengaluru, KARNATAKA", description: "MSRIT is one of the top engineering colleges in Karnataka with excellent placement record.", rating: 4.6, fees: "₹1,00,000 - ₹1,80,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 7] },
    { id: 1066, collegeCode: "E078", name: "Maharaja Institute of Technology", location: "Belawadi, Mandya, KARNATAKA", description: "MIT Mandya offers quality technical education with modern infrastructure.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 5, 7] },
    { id: 1067, collegeCode: "E079", name: "Malnad College of Engineering", location: "Rangoli Halla, Hassan, KARNATAKA", description: "MCE is known for its academic excellence and research facilities.", rating: 4.3, fees: "₹90,000 - ₹1,60,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 7] },
    { id: 1068, collegeCode: "E080", name: "Mangalore Institute of Technology & Engineering", location: "Moodbidri, Mangaluru, KARNATAKA", description: "MITE provides quality engineering education with excellent infrastructure.", rating: 4.2, fees: "₹85,000 - ₹1,50,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1069, collegeCode: "E081", name: "Moodalakatte Institute of Technology", location: "Moodalakatte, Kundapura, KARNATAKA", description: "MIT Kundapura offers various engineering programs with experienced faculty.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 5, 7] },
    { id: 1070, collegeCode: "E082", name: "Maharaja Institute of Technology", location: "Thandavapura, Mysuru, KARNATAKA", description: "MIT Mysuru provides quality technical education with modern facilities.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 6] },
    { id: 1071, collegeCode: "E083", name: "Mysuru Royal Institute of Technology", location: "Palahallli, Mandya District, KARNATAKA", description: "MRIT offers various engineering programs with a focus on practical skills.", rating: 3.8, fees: "₹65,000 - ₹1,10,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1072, collegeCode: "E084", name: "Nagarjuna College of Engineering & Technology", location: "Devanahalli Bengaluru, KARNATAKA", description: "NCET provides quality engineering education with excellent infrastructure.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 7] },
    { id: 1073, collegeCode: "E085", name: "The National Institute of Engineering, North Campus", location: "Koorgalli, Mysuru, KARNATAKA", description: "NIE North Campus offers various engineering programs with experienced faculty.", rating: 4.4, fees: "₹90,000 - ₹1,60,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 7] },
    { id: 1074, collegeCode: "E088", name: "Navodaya Institute of Technology", location: "Bijangera, Raichur, KARNATAKA", description: "NIT Raichur provides quality technical education with modern facilities.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1075, collegeCode: "E089", name: "P.E.S.College of Engineering", location: "PES College Road, Mandya, KARNATAKA", description: "PESCE is known for its academic excellence and research opportunities.", rating: 4.2, fees: "₹85,000 - ₹1,50,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 7] },
    { id: 1076, collegeCode: "E090", name: "PES Institute of Technology & Management", location: "Shivamogga, KARNATAKA", description: "PESITM offers various engineering programs with a focus on industry-ready skills.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 5] },
    { id: 1077, collegeCode: "E094", name: "Proudhadevaraya Institute of Technology", location: "TB Dam Road, Hosapete, KARNATAKA", description: "PIT provides quality engineering education with experienced faculty.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 5, 7] },
    { id: 1078, collegeCode: "E095", name: "R V College of Engineering", location: "Mysore Road, Bengaluru, KARNATAKA", description: "RVCE is one of the top engineering colleges in Karnataka with excellent placement record.", rating: 4.7, fees: "₹1,00,000 - ₹1,80,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 7] },
    { id: 1079, collegeCode: "E096", name: "R.L. Jalappa Institute of Technology", location: "Kodigehalli, Doddaballapur, KARNATAKA", description: "RLJIT offers quality technical education with modern infrastructure.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1080, collegeCode: "E097", name: "R.R. Institute of Technology", location: "Chikkabanavara, Bengaluru, KARNATAKA", description: "RRIT provides various engineering programs with experienced faculty.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 5, 6] },
    { id: 1081, collegeCode: "E098", name: "R.T.E. Society's Rural Engineering College", location: "Hulkoti, Gadag, KARNATAKA", description: "REC offers quality engineering education with a focus on rural development.", rating: 3.8, fees: "₹65,000 - ₹1,10,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 7] },
    { id: 1082, collegeCode: "E099", name: "Raja Rajeswari College of Engineering", location: "Kumbalgodu, Bengaluru, KARNATAKA", description: "RRCE provides quality technical education with excellent infrastructure.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 5] },
    { id: 1083, collegeCode: "E100", name: "Rajeev Institute of Technology", location: "BM Bypass Road, Hassan, KARNATAKA", description: "RIT Hassan offers various engineering programs with modern facilities.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 7] },
    { id: 1084, collegeCode: "E101", name: "Rajiv Gandhi Institute of Technology", location: "R T Nagar Post, Bengaluru, KARNATAKA", description: "RGIT provides quality engineering education with experienced faculty.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 5] },
    { id: 1085, collegeCode: "E102", name: "Rao Bahadur Y Mahabaleswarappa Engineering College", location: "Cantonment, Ballari, KARNATAKA", description: "RYMEC offers quality technical education with a focus on practical skills.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 6] },
    { id: 1086, collegeCode: "E104", name: "RNS Institute of Technology", location: "R R Nagar Post, Bengaluru, KARNATAKA", description: "RNSIT is known for its academic excellence and placement opportunities.", rating: 4.3, fees: "₹90,000 - ₹1,60,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 7] },
    { id: 1087, collegeCode: "E105", name: "Bheemanna Khandre Institute of Technology", location: "Bhalki, Bidar, KARNATAKA", description: "BKIT provides quality engineering education with modern infrastructure.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 5, 7] },
    { id: 1088, collegeCode: "E107", name: "SJB Institute of Technology", location: "Kengeri, Bengaluru, KARNATAKA", description: "SJBIT offers various engineering programs with excellent facilities.", rating: 4.2, fees: "₹85,000 - ₹1,50,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3] },
    { id: 1089, collegeCode: "E108", name: "S J C Institute of Technology", location: "BB Road, Chikkaballapur, KARNATAKA", description: "SJCIT provides quality technical education with experienced faculty.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1090, collegeCode: "E109", name: "S.E.A. College of Engineering & Technology", location: "K R Puram, Bengaluru, KARNATAKA", description: "SEACET offers various engineering programs with a focus on practical skills.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 5, 7] },
    { id: 1091, collegeCode: "E110", name: "SSET's S.G. Balekundri Institute of Technology", location: "Shivabasava Nagar, Belagavi, KARNATAKA", description: "SGBIT provides quality engineering education with modern infrastructure.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 6] },
    { id: 1092, collegeCode: "E112", name: "Sahyadri College of Engineering and Management", location: "Adyar, Mangaluru, KARNATAKA", description: "SCEM is known for its academic excellence and research facilities.", rating: 4.3, fees: "₹90,000 - ₹1,60,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 7] },
    { id: 1093, collegeCode: "E113", name: "Sai Vidya Institute of Technology", location: "Rajan Kunte, Bengaluru, KARNATAKA", description: "SVIT offers quality technical education with excellent infrastructure.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1094, collegeCode: "E114", name: "Sambhram Institute of Technology", location: "Jalahalli East, Bengaluru, KARNATAKA", description: "SaIT provides various engineering programs with experienced faculty.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 7] },
    { id: 1095, collegeCode: "E116", name: "SAPTHAGIRI NPS UNIVERSITY", location: "Hesaraghatta Main Road, Bengaluru, KARNATAKA", description: "SNPSU offers quality education in various disciplines including engineering.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 4, 8] },
    { id: 1096, collegeCode: "E117", name: "SDM College of Engineering & Technology", location: "Kalaghatagi, Dharwad, KARNATAKA", description: "SDMCET (Tulu Minority) provides quality technical education with modern facilities.", rating: 4.2, fees: "₹85,000 - ₹1,50,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 7] },
    { id: 1097, collegeCode: "E118", name: "SDM Institute of Technology", location: "Ujjire, Dakshina Kannada, KARNATAKA", description: "SDMIT (Tulu Minority) offers various engineering programs with a focus on practical skills.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1098, collegeCode: "E119", name: "SECAB Institute of Engineering &Technology", location: "Nauraspur-Bagalkot Road, Vijayapura, KARNATAKA", description: "SIET provides quality engineering education with experienced faculty.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 5, 7] },
    { id: 1099, collegeCode: "E121", name: "Sri Sairam College of Engineering", location: "Anekal, Bengaluru, KARNATAKA", description: "SSCE offers various engineering programs with excellent infrastructure.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3] },
    { id: 1100, collegeCode: "E122", name: "Shree Devi Institute of Technology", location: "Kenjar, Mangaluru, KARNATAKA", description: "SDIT provides quality technical education with modern facilities.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1101, collegeCode: "E123", name: "Shri Madhwa Vadiraja Institute of Technology & Management", location: "Bantakal, Udupi, KARNATAKA", description: "SMVITM offers various engineering programs with experienced faculty.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 7] },
    { id: 1102, collegeCode: "E124", name: "Shridevi Institute of Engineering & Technology", location: "Sira Road, Tumakuru, KARNATAKA", description: "SIET provides quality engineering education with a focus on practical skills.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 6] },
    { id: 1103, collegeCode: "E125", name: "Siddaganga Institute of Technology", location: "B H Road, Tumakuru, KARNATAKA", description: "SIT is known for its academic excellence and research facilities.", rating: 4.4, fees: "₹90,000 - ₹1,60,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 3, 7] },
    { id: 1104, collegeCode: "E126", name: "Sir M.Visvesvaraya Institute of Technology", location: "Yelahanka, Bengaluru, KARNATAKA", description: "Sir MVIT offers quality technical education with excellent infrastructure.", rating: 4.2, fees: "₹85,000 - ₹1,50,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 5] },
    { id: 1105, collegeCode: "E127", name: "S J M Institute of Technology", location: "NH 4 Bye-pass, Chitradurga, KARNATAKA", description: "SJMIT provides various engineering programs with experienced faculty.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 7] },
    { id: 1106, collegeCode: "E128", name: "Smt. Kamala and Sri Venkappa M. Agadi College of Engineering & Technology", location: "Laxmeswar, Gadag, KARNATAKA", description: "KVA provides quality engineering education with modern facilities.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 5, 6] },
    { id: 1107, collegeCode: "E132", name: "Sri Krishna Institute of Technology", location: "Chikkabanavara, Bengaluru, KARNATAKA", description: "SKIT offers various engineering programs with a focus on practical skills.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 7] },
    { id: 1108, collegeCode: "E136", name: "Sri Taralabalu Jagadguru Institute of Technology", location: "Haveri Dist., Ranebennur, KARNATAKA", description: "STJIT provides quality technical education with experienced faculty.", rating: 3.9, fees: "₹70,000 - ₹1,20,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] },
    { id: 1109, collegeCode: "E137", name: "Sri Venkateshwara College of Engineering", location: "KIAL Road, Bengaluru, KARNATAKA", description: "SVCE offers quality engineering education with excellent infrastructure.", rating: 4.1, fees: "₹80,000 - ₹1,40,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 2, 7] },
    { id: 1110, collegeCode: "E138", name: "Srinivas Institute of Technology", location: "Hampankatta, Mangaluru, KARNATAKA", description: "SIT Mangaluru provides various engineering programs with modern facilities.", rating: 4.0, fees: "₹75,000 - ₹1,30,000 per year", imageUrl: "/placeholder.svg", degreesOffered: [1, 3, 5] }
  ];
  
  // Return the colleges list
  return colleges;
};

