
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxmobzqjegexmjzjfjfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4bW9ienFqZWdleG1qempmamZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzAwNjQsImV4cCI6MjA2MjkwNjA2NH0.GsHBlusVlKozBYZGEa6f1ABoayP5Kj6dUQXlMUdGPf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
